/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e5e2e1",
        "primary-fixed-dim": "#b3cdb7",
        "tertiary-fixed": "#ffe088",
        "secondary-container": "#bdefc3",
        "on-surface-variant": "#434843",
        "inverse-on-surface": "#f3f0ef",
        "on-primary-container": "#809985",
        "inverse-primary": "#b3cdb7",
        "on-secondary-fixed-variant": "#234f30",
        "on-primary-fixed-variant": "#354c3b",
        "secondary-fixed-dim": "#a2d2a8",
        "surface-variant": "#e5e2e1",
        "error": "#ba1a1a",
        "surface-dim": "#dcd9d9",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#f0edec",
        "background": "#fcf9f8",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-fixed-variant": "#574500",
        "tertiary-fixed-dim": "#e9c349",
        "tertiary-container": "#cca730",
        "on-tertiary-container": "#4f3d00",
        "surface-bright": "#fcf9f8",
        "on-error": "#ffffff",
        "on-secondary-container": "#426e4b",
        "outline-variant": "#c3c8c1",
        "surface-container-high": "#ebe7e7",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "surface": "#fcf9f8",
        "tertiary": "#735c00",
        "on-secondary-fixed": "#00210b",
        "on-secondary": "#ffffff",
        "primary": "#051b0e",
        "outline": "#737972",
        "primary-container": "#1a3021",
        "secondary": "#3c6846",
        "inverse-surface": "#313030",
        "surface-tint": "#4c6452",
        "on-surface": "#1c1b1b",
        "error-container": "#ffdad6",
        "secondary-fixed": "#bdefc3",
        "on-tertiary-fixed": "#241a00",
        "on-primary-fixed": "#0a2012",
        "primary-fixed": "#cfe9d2",
        "on-background": "#1c1b1b",
      },
      borderRadius: {
        sm: "0.375rem",
        DEFAULT: "0.75rem",
        lg: "1rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "unit": "8px",
        "margin-mobile": "20px",
        "gutter": "24px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-xl": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "100%",
      },
    },
  },
  plugins: [],
}
